from django.urls 	import path, re_path
from django.views.generic import TemplateView
from FrontEndApp	import views
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("request_password/",views.RequestResetPasswordFormView.as_view(), name="request_reset_password"),
    path("reset/password/<uuid:uid>/",views.ResetPasswordFormView.as_view(), name="reset_password"),
    path("reset/temporal_password/",views.ResetTemporalPasswordFormView.as_view(), name="reset_temporal_password"),
    path('auth/2fa/', views.authenticate_2fa, name='authenticate_2fa'),
    path('auth/2fa/send_email/', views.email_2fa, name='email_2fa'),
    path("reservation_page/create/", views.ReservationCreateView.as_view(), name="reservation_page"),
    path("reservation_page/update/<uuid:uid>/", views.ReservationCreateView.as_view(), name="reservation_page_details"),
    path("sale_page/", views.SaleView.as_view(), name="sale_page"),
    path("sale_page/<uuid:uid>/", views.SaleView.as_view(), name="sale_page"),
    re_path(r'catalogs', views.IndexView.as_view()),
    re_path(r'profile', views.IndexView.as_view()),
    re_path(r'user_extension', views.IndexView.as_view()),
    re_path(r'user_admin', views.IndexView.as_view()),
    re_path(r'requests', views.IndexView.as_view()),
    re_path(r'permission_groups', views.IndexView.as_view()),
    re_path(r'provider_costs', views.IndexView.as_view()),
    re_path(r'permission_group', views.IndexView.as_view()),
    re_path(r'reservation', views.IndexView.as_view()),
    re_path(r'reservations', views.IndexView.as_view()),
    re_path(r'operations', views.IndexView.as_view()),
    re_path(r'allotments', views.IndexView.as_view()),
    re_path(r'store_cards', views.IndexView.as_view()),
    re_path(r'store_card', views.IndexView.as_view()),
    re_path(r'sale', views.IndexView.as_view()),
    re_path(r'sales', views.IndexView.as_view()),
    re_path(r'flights', views.IndexView.as_view()),
    re_path(r'flight', views.IndexView.as_view()),
    re_path(r'pick_up', views.IndexView.as_view()),
    re_path(r'pick_ups', views.IndexView.as_view()),
    path(r'', views.IndexView.as_view()),
]